#This yaml file is for checking the latest verion of prometheus-operator and to test the PrometheusRule crd of pormetheus-operator.
#run kubectl create ns alerting
#helm install --name helm coreos/prometheus-operator --namespace alerting

#Setup the alertmanager 

#--------------------alert-managers------------------#
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
  replicas: 1
---
#--------------------alert-managers-configuration-secret------------------#
Version: v1
kind: Secret   #todo make it data encoded.
metadata:
  name: alertmanager-alertmanager
data:



---
#--------------------service to access the alert manager----------------#
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: alertmanager
---
#--------------------ingress rule for the alert manager service optional --------#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-tls-cert-header: "false"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: haproxy
  name: alertmanager-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: alertmanager-svc
          servicePort: 9093
        path: /alrt
status:
  loadBalancer: {}
---